### ISSUE TITLE
Add support for OFF button

### ISSUE THREAD

**Issue by teejay-87** [anotherjulien/MyHOME#2]
I would be interesting to have support for the "OFF" button. I have two off them, one at the front door, one at the garage.
They send a special signal to the bus and then all lights are turned off.

If you need support in determining the "special signal", I can help.

![image](https://user-images.githubusercontent.com/17051981/101162882-337d1700-3633-11eb-9d45-94b8d135d7f3.png)

**Comment by teejay-87** [comment]
Sorry, maybe the request is not clear enough.
The problem is that if I physically press the "OFF" button, the component does not detect the "special signal" and all light entities in HA remains ON.

**Comment by anotherjulien** [comment]
If I understand correctly this is a switch that sends a "general off" light command on the bus, right?
If so, the integration receives it, and packs it into an event (myhome_general_light_event).
You can trigger anything you like with that event.
The problem however is that if the light itself does not reply to that command with its new status, the integration has no way to know if the light correctly responded to it.

I think one possible workaround would be to use the "myhome_general_light_event" to trigger a "send_message" service with message "*#1*0##" and that would force all the lights to reply with their current state.
It might be worth including a 0.5s delay to make sure all lights received the general OFF commands before sending the status update request.

Would you be able to create an automation for that?

**Comment by teejay-87** [comment]
Thanks for the quick reply.
I'll try to detect that event and use it within an automation, and let you know

**Comment by teejay-87** [comment]
And also this one works!

**Comment by teejay-87** [comment]
For anyone interested, I used this automation:

’’’
alias: Rileva comando OFF generale MyHome
description: ''
trigger:
  - platform: event
    event_type: myhome_general_light_event
condition: []
action:
  - delay: '0.1'
  - service: myhome.send_message
    data:
      message: '*#1*0##'
mode: single
’’’

A 0.1 sec delay seems sufficient.

**Comment by alessandro-lac** [comment]
Hi teejay-87, 
I'd like to test it out with a general button I have next to the entry door. 
Unfortunately, I can't seem to listen for CEN/CEN+ events, is there anything I should do in order to see those events and respond to them? I tried registering to a general myhome_general_light_event into the developer tools, but nothing fires when I press buttons.


Thanks, 
Ale

**Comment by teejay-87** [comment]
> Hi teejay-87,
> I'd like to test it out with a general button I have next to the entry door.
> Unfortunately, I can't seem to listen for CEN/CEN+ events, is there anything I should do in order to see those events and respond to them? I tried registering to a general myhome_general_light_event into the developer tools, but nothing fires when I press buttons.
> 
> Thanks,
> Ale

That's strange indeed.
Before using the automations, I tried exactly what you described with Dev tools in HA, and the events gets registered correctly.

Try with the automation anyway.

**Comment by caiosweet** [comment]
> Hi teejay-87,
> I'd like to test it out with a general button I have next to the entry door.
> Unfortunately, I can't seem to listen for CEN/CEN+ events, is there anything I should do in order to see those events and respond to them? I tried registering to a general myhome_general_light_event into the developer tools, but nothing fires when I press buttons.
> 
> Thanks,
> Ale

I think we're out of the context of the issue, but have you read the readme?
For the cen/cen+ commands the event is different.
[cencen-event](https://github.com/anotherjulien/MyHOME#cencen-events)

`myhome_cenplus_event`
`myhome_cen_event`

In any case, I have created an automation for tests, I use telegram to get me the test notifications.
```yaml
automation:
  #--------------------------------------
  # CEN/CEN+ events - Other events
  #--------------------------------------
  - alias: MyHome Event
    description: "Notification MyHome Event"
    initial_state: true
    mode: queued
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: myhome_cenplus_event
      - platform: event
        event_type: myhome_cen_event
      - platform: event
        event_type: myhome_general_light_event
      - platform: event
        event_type: myhome_area_light_event
      - platform: event
        event_type: myhome_group_light_event
    action:
      - variables:
          title: '{{trigger.description}}'
          data: '{{trigger.event.data}}'
      - service: notify.telegram
        data:
          message: |
            MyHome {{title|replace('*','\*')|replace('_','\_')}}

            {{data|replace('*','\*')|replace('_','\_')}}
```
