### ISSUE TITLE
Auxiliary sensors ignored?

### ISSUE THREAD

**Issue by stepir** [anotherjulien/MyHOME#28]
Hi

I have 9 Auxiliary sensors used in my system for detecting water leaks. They are connected to basic contact interface 3477 (https://catalogo.bticino.it/BTI-3477-IT) and configured in my web server F454 for sending alters.

I tried configuring them with:

```
binary_sensor:
  - platform: myhome
    devices:
      motion_sensor:
        where: '1'
        who: '9'
        name: Motion living room
        class: motion
        manufacturer: BTicino
        model: L4610
```

However HA is totally ignoring this config - not producing the creation of the binary sensor but also not logging anything at all? any help?

Thanks in advance!
