### ISSUE TITLE
Home assistant 2022.8.0 and Integration stop working after reboot OS

### ISSUE THREAD

**Issue by viperxeno** [anotherjulien/MyHOME#57]
Hi, I have this problem with this integration after upgrade home assistant to 2022.8.0. after reboot home assistant, integration stop working and doesn't recognise bticino my home server 1, it need to manual reboot integration for start working.

Attached video...

https://user-images.githubusercontent.com/105608752/183845258-f5fa9278-bb39-468b-9790-076268646388.mp4

@anotherjulien

**Comment by chochobo78** [comment]
Hi.
I have the same problem, the power and energy entities do not charge me.  Is there a way to create a script that after the restart of homeassistant passed x seconds it restarts the integration?

**Comment by ubettoni** [comment]
This is a script created by Gabriele Dal Toe and posted on community home assistant forum:

```
alias: Reload MyHome at Start
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: hassio.addon_stdin
    data:
      addon: myhome
      input: reload
mode: single
```
