### ISSUE TITLE
WHO2 window blinds status "unknown"

### ISSUE THREAD

**Issue by cyrilcordoba** [anotherjulien/MyHOME#84]
Hello @anotherjulien 

First of all let me thank you for the great work done on this integration. I'm user of Jeedom, transitioning to HA. 

I'm trying to get automation with window blinds & shutters but the status is "unknown", when not "closing" or "opening" . 

```
# Device configuration
f454:
  mac: "00:xx:xx:xx:xx:31"
  cover:
    chambrecamillefenetre:
      where: "86"
      name: Chambre Camille Fenêtre
      advanced: False
      manufacturer: Legrand
      model: F411
    chambrecamillestore:
      where: "88"
      name: Chambre Camille Store
      advanced: False
      manufacturer: Legrand
      model: F411
```

I've tried to put advanced to True & False, it doesn't change the status. I'm also wondering how this is solved in Jeedom as I don't see frames indicating the stauts.

```
[2023-04-25	14:06:32][INFO]	:	Reçu	sur	Jeedom	:	*2*1000#0*88##
[2023-04-25	14:06:32][INFO]	:	Reçu	sur	Jeedom	:	*2*0*88##
[2023-04-25	14:06:49][INFO]	:	Reçu	sur	Jeedom	:	*2*1000#0*86##
[2023-04-25	14:06:49][INFO]	:	Reçu	sur	Jeedom	:	*2*0*86##
[2023-04-25	14:06:49][INFO]	:	Reçu	sur	Jeedom	:	*2*1000#1*86##
[2023-04-25	14:06:49][INFO]	:	Reçu	sur	Jeedom	:	*2*1*86##
[2023-04-25	14:07:04][INFO]	:	Reçu	sur	Jeedom	:	*2*1000#0*86##
[2023-04-25	14:07:04][INFO]	:	Reçu	sur	Jeedom	:	*2*0*86##
[2023-04-25	14:07:12][INFO]	:	Reçu	sur	Jeedom	:	*2*1000#0*86##
[2023-04-25	14:07:12][INFO]	:	Reçu	sur	Jeedom	:	*2*0*86##
[2023-04-25	14:07:12][INFO]	:	Reçu	sur	Jeedom	:	*2*1000#2*86##
[2023-04-25	14:07:12][INFO]	:	Reçu	sur	Jeedom	:	*2*2*86##
[2023-04-25	14:07:27][INFO]	:	Reçu	sur	Jeedom	:	*2*1000#0*86##
[2023-04-25	14:07:27][INFO]	:	Reçu	sur	Jeedom	:	*2*0*86##
```
Can you let me know if this is a known behavior/issue ? I can try & dig into the Jeedom code to see how they solved it in such a case.

Best regards
Cyril
